package task3.enum

enum class TestAction {
    START_OBSERVATION,
    FEEL_CONTEMPT,
    FEEL_DESPERATION,
    ACTIVATE_LOGICAL_SCHEMES,
    MANIPULATE_LOGICAL_SCHEMES,
    APPLY_PHYSICAL_FORCE,
    COMPARE_COMPONENTS,
    ANALYZE_BRAIN_CELLS,
    MEASURE_HYDROGEN_LEVEL
}